# Generated by Django 6.0 on 2025-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.IntegerField(blank=True, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anulado', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('rif_cedula_identidad', models.CharField(max_length=50)),
                ('direccion_inmueble', models.TextField()),
                ('ente_liquidado', models.CharField(max_length=255)),
                ('categoria1', models.BooleanField(default=False)),
                ('categoria2', models.BooleanField(default=False)),
                ('categoria3', models.BooleanField(default=False)),
                ('categoria4', models.BooleanField(default=False)),
                ('categoria5', models.BooleanField(default=False)),
                ('categoria6', models.BooleanField(default=False)),
                ('categoria7', models.BooleanField(default=False)),
                ('categoria8', models.BooleanField(default=False)),
                ('categoria9', models.BooleanField(default=False)),
                ('categoria10', models.BooleanField(default=False)),
                ('gastos_administrativos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_dia', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_monto_bs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_transferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
            ],
            options={
                'db_table': 'recibos_pago',
            },
        ),
    ]
