# Generated by Django 6.0 on 2025-12-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos_pago',
            name='concepto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
