# Generated by Django 6.0 on 2025-12-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'verbose_name': 'Recibo de Pago', 'verbose_name_plural': 'Recibos de Pago'},
        ),
        migrations.AlterField(
            model_name='recibo',
            name='anulado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero_recibo',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero_transferencia',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='rif_cedula_identidad',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='total_monto_bs',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddIndex(
            model_name='recibo',
            index=models.Index(fields=['anulado', '-fecha', '-numero_recibo'], name='recibos_pag_anulado_cb71fb_idx'),
        ),
    ]
