# Generated by Django 6.0 on 2025-12-06 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_recibos_pago_concepto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibos_pago',
            options={'verbose_name': 'Recibo de Pago', 'verbose_name_plural': 'Recibos de Pago'},
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='categoria9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='conciliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='direccion_inmueble',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='ente_liquidado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='estado',
            field=models.CharField(default='Pagado', max_length=50),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='gastos_administrativos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='numero_de_transferencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='rif_cedula_identidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='tasa_dia',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='total_monto_bs',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibos_pago',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
