# Generated by Django 6.0 on 2025-12-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0003_alter_recibos_pago_options_recibos_pago_anulado_and_more'),
    ]

    operations = [
    ]
