# Generated by Django 6.0 on 2025-12-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0004_auto_20251206_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibos_pago',
            old_name='numero_de_transferencia',
            new_name='numero_transferencia',
        ),
        migrations.RemoveField(
            model_name='recibos_pago',
            name='usuario_creador',
        ),
    ]
